"""empty message

Revision ID: baee543e261e
Revises: a569a5fff1e2
Create Date: 2016-10-10 16:42:29.708454

"""

# revision identifiers, used by Alembic.
revision = 'baee543e261e'
down_revision = 'a569a5fff1e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beer_name', sa.String(length=80), nullable=False),
    sa.Column('abv', sa.Numeric(), nullable=False),
    sa.Column('hoppiness', sa.Numeric(), nullable=False),
    sa.Column('bitterness', sa.Numeric(), nullable=False),
    sa.Column('fruitiness', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beer_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beers')
    ### end Alembic commands ###
